### ISSUE TITLE
SetUp docs

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/librarian#8]
Although we  do not have yet a lot of documentation we probably migrate part of the documentation form the [Library](https://github.com/Nautilus-Cyberneering/chinese-ideographs) to this repo. We do not have a website for the documentation on the Libary. I think we could setup one here. I was looking for alternatives using [GitHub Pages](https://pages.github.com/):

- [Just the Docs](https://pmarsceill.github.io/just-the-docs/). Responsive Jekyll theme that is easily customizable and hosted on GitHub Pages
- [MkDocs](https://www.mkdocs.org/). MkDocs is a fast, simple and downright gorgeous static site generator.

Repos:
- https://github.com/mkdocs/mkdocs/ (193 contributors, used by 16k)
- https://github.com/pmarsceill/just-the-docs (48 contributors, used by 3.6k)

What I like from MkDocs:

- [Versioning](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/). It seems to be available only for the Material for MkDocs fork.
- [Themes](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes).

**Comment by cgbosse** [comment]
Looks good to me.

**Comment by josecelano** [comment]
For some types of documents we should use GitHub files: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#supported-file-types

**Comment by josecelano** [comment]
Installation was very easy:

```
poetry add --dev mkdocs
mkdocs new .
```
Now I want to automatically deploy to ghpages. There are some actions:

- https://github.com/marketplace/actions/deploy-mkdocs
- https://github.com/marketplace/actions/mkdocs-action
- https://github.com/marketplace/actions/tangy-mkdocs-build-action
- https://github.com/marketplace/actions/mkdocs-github-deploy
- https://github.com/marketplace/actions/mkdocs-github-pages-releaser

But the MkDocs has a command to do it: https://www.mkdocs.org/user-guide/deploying-your-docs/#project-pages. I'm going to try first with this option.

**Comment by josecelano** [comment]
We have the documentation live on: https://nautilus-cyberneering.github.io/librarian/
